// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	NotificationInfo
	NotificationInfoSet
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotificationInfo struct {
	Alert     string `protobuf:"bytes,1,opt,name=alert" json:"alert,omitempty"`
	Receiver  string `protobuf:"bytes,2,opt,name=receiver" json:"receiver,omitempty"`
	Resolved  bool   `protobuf:"varint,3,opt,name=resolved" json:"resolved,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *NotificationInfo) Reset()                    { *m = NotificationInfo{} }
func (m *NotificationInfo) String() string            { return proto.CompactTextString(m) }
func (*NotificationInfo) ProtoMessage()               {}
func (*NotificationInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NotificationInfoSet struct {
	Infos []*NotificationInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
}

func (m *NotificationInfoSet) Reset()                    { *m = NotificationInfoSet{} }
func (m *NotificationInfoSet) String() string            { return proto.CompactTextString(m) }
func (*NotificationInfoSet) ProtoMessage()               {}
func (*NotificationInfoSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NotificationInfoSet) GetInfos() []*NotificationInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*NotificationInfo)(nil), "msg.NotificationInfo")
	proto.RegisterType((*NotificationInfoSet)(nil), "msg.NotificationInfoSet")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x06, 0x32, 0x95, 0xea, 0xb8, 0x04, 0xfc, 0xf2, 0x4b,
	0x32, 0xd3, 0x32, 0x93, 0x13, 0x4b, 0x32, 0xf3, 0xf3, 0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0x44, 0xb8,
	0x58, 0x13, 0x73, 0x52, 0x8b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21,
	0x29, 0x2e, 0x8e, 0xa2, 0xd4, 0xe4, 0xd4, 0xcc, 0xb2, 0xd4, 0x22, 0x09, 0x26, 0xb0, 0x04, 0x9c,
	0x0f, 0x91, 0x2b, 0xce, 0xcf, 0x29, 0x4b, 0x4d, 0x91, 0x60, 0x06, 0xca, 0x71, 0x04, 0xc1, 0xf9,
	0x42, 0x32, 0x5c, 0x9c, 0x25, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x12, 0x2c, 0x40,
	0x49, 0xe6, 0x20, 0x84, 0x80, 0x92, 0x13, 0x97, 0x30, 0xba, 0xfd, 0xc1, 0xa9, 0x25, 0x42, 0xda,
	0x5c, 0xac, 0x99, 0x40, 0x66, 0x31, 0xd0, 0x09, 0xcc, 0x1a, 0xdc, 0x46, 0xa2, 0x7a, 0x20, 0x67,
	0xa3, 0x2b, 0x0c, 0x82, 0xa8, 0x49, 0x62, 0x03, 0xfb, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0xe0, 0x8a, 0x7f, 0xdc, 0x00, 0x00, 0x00,
}
